name = 'pgrange/aiken_backtrace'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project 'pgrange/aiken_backtrace'"

[repository]
user = 'pgrange'
project = 'aiken_backtrace'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = 'main'
source = 'github'
